### ISSUE TITLE
About re-parametrization for low variance gradient computation

### ISSUE THREAD

**Issue by heyzude** [facebookresearch/online-dt#1]
Hi, and thanks for the nice work!

I read the code, and just wonder which part deals with the re-parameterization technique mentioned in your paper on page 4.

I think in the code it just samples action from a normal distribution, but doesn't re-param something.

**Comment by enosair** [comment]
https://github.com/facebookresearch/online-dt/blob/main/decision_transformer/models/decision_transformer.py#L84

The `rsample()` function uses the re-parametrization automatically, see https://pytorch.org/docs/stable/distributions.html#pathwise-derivative

**Comment by heyzude** [comment]
Oh thanks! Yeap!
