### ISSUE TITLE
Unused ordering array in TransformSamplingSubTraj?

### ISSUE THREAD

**Issue by 4rChon** [facebookresearch/online-dt#10]
Hi, I've been going over the code to understand how it works and I've come across the following in `data.py`:

https://github.com/facebookresearch/online-dt/blob/c376fa113ba34bcd422da44598e8c2433c06a590/data.py#L87C1-L89C50

```python
        ordering = np.arange(tlen)
        ordering[timesteps >= MAX_EPISODE_LEN] = -1
        ordering[ordering == -1] = ordering.max()
```

which is returned by calling an instance of the TransformSamplingSubTraj: 
https://github.com/facebookresearch/online-dt/blob/c376fa113ba34bcd422da44598e8c2433c06a590/data.py#L126

However when this value eventually makes its way to the `forward` call of the `DecisionTransformer`, it seems like it is unused.

`timesteps` is used as an input to the `order_embeddings` and `ordering` is not referenced in the function:

https://github.com/facebookresearch/online-dt/blob/c376fa113ba34bcd422da44598e8c2433c06a590/decision_transformer/models/decision_transformer.py#L221

What is the purpose of this `ordering` array?

Thanks.

**Comment by enosair** [comment]
I believe this is something we were experimenting with, but not used in the end.
