### ISSUE TITLE
multiprocessing, TypeError: _generator_ctor() takes from 0 to 1 positional arguments but 2 were given

### ISSUE THREAD

**Issue by yjl-001** [facebookresearch/online-dt#6]
```
Traceback (most recent call last):
  File "main.py", line 520, in <module>
    experiment()
  File "main.py", line 443, in __call__
    eval_envs = SubprocVecEnv(
  File "/home/yujianlong/.conda/envs/odt/lib/python3.8/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 112, in __init__
    observation_space, action_space = self.remotes[0].recv()
  File "/home/yujianlong/.conda/envs/odt/lib/python3.8/multiprocessing/connection.py", line 252, in recv
    return _ForkingPickler.loads(buf.getbuffer())
TypeError: _generator_ctor() takes from 0 to 1 positional arguments but 2 were given
```

locate source code as followed：
```python
def recv(self):
        """Receive a (picklable) object"""
        self._check_closed()
        self._check_readable()
        buf = self._recv_bytes()
        print(str(id(buf))+ ": " + str(buf))
        return _ForkingPickler.loads(buf.getbuffer())
```

when I run `python main.py`, the above error occors. How can I fix the error? It seems that `_ForkingPickler.loads(buf.getbuffer())` gets two arguments, then I print the variable `buf`, finding:
```
139731026921008: <_io.BytesIO object at 0x7f15aa394630>
139966793394432: <_io.BytesIO object at 0x7f4c8f002900>
```
It seems that there are two processes deal with the function`recv` at same time?

**Comment by enosair** [comment]
`_generator_ctor(...)` is from numpy random number generator https://github.com/numpy/numpy/blob/main/numpy/random/_pickle.py#L40

When you create the eval envs, gym will call numpy random number generator for initialization. I suspect this is a numpy version issue. See https://github.com/ray-project/ray/issues/31293 and https://discuss.ray.io/t/error-randomnumbergenerator/8956.

The code runs fine on my end. If downgrading numpy version cannot help, try tweaking other packages' versions, e.g. gym, stablebaseline3 and so on.

**Comment by yjl-001** [comment]
> `_generator_ctor(...)` is from numpy random number generator https://github.com/numpy/numpy/blob/main/numpy/random/_pickle.py#L40
> 
> When you create the eval envs, gym will call numpy random number generator for initialization. I suspect this is a numpy version issue. See [ray-project/ray#31293](https://github.com/ray-project/ray/issues/31293) and https://discuss.ray.io/t/error-randomnumbergenerator/8956.
> 
> The code runs fine on my end. If downgrading numpy version cannot help, try tweaking other packages' versions, e.g. gym, stablebaseline3 and so on.

Thank you, this is suitable for me.
